FROM mcr.microsoft.com/devcontainers/javascript-node:0-20

# Install postgresql client (optional, in case you want to connect to PostgreSQL via cli)
RUN apt-get update && apt-get install -y postgresql-client